name: Create Tag on Merge to develop branch

on:
  push:
    branches:
      - develop

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Tag
        run: |
          # Create the tag
          TAG_NAME="dev-deploy-1"
          git tag $TAG_NAME 

          # Push the tag to the remote repository
          git push origin $TAG_NAME

          
